packages:
  - python-3.12.10
  - python-3.12.10-atls
  - python-3.12.10-sccoda
  - python-3.10.11
  - catalogue

catalog:
  'turbo': ^2.5.4
  '@changesets/cli': ^2.29.5
  '@platforma-sdk/package-builder': ^3.5.2
  'tar': ^7.4.3
  'unzipper': ^0.12.3
  '@platforma-sdk/blocks-deps-updater': 2.0.0
