packages:
  - builder
  - python-3.12.10
  - python-3.12.10-empty
  - python-3.12.10-atls
  - python-3.12.10-sccoda
  - python-3.12.10-rapids
  - python-3.12.10-h5ad
  - catalogue

catalog:
  'turbo': ^2.5.4
  '@changesets/cli': ^2.29.5
  '@platforma-sdk/package-builder': ^3.6.0
  '@platforma-sdk/blocks-deps-updater': 2.0.0
  'tsx': ^4.20.2
